# Application
spring.application.name=hotelsync-hms

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/hotelsync_db
spring.datasource.username=root
spring.datasource.password=Sumit@2408
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080


#this is the line we chaneg that you rfind for at the time of the pr